repo: 'icon-navigation'
canvasCourse: 'web-dev-3'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    outline: true
    has:
      - ['link[href*="Abhaya+Libre:400,700"]', 'The Google Font, `Abhaya Libre` (regular & bold) is missing']
      - ['link[href*="modules.css"] + link[href*="grid.css"]', 'The `modules.css` file must come before the `grid.css` file']
      - ['link[href*="grid.css"] + link[href*="type.css"]', 'The `grid.css` file must come before the `type.css` file']
      - ['link[href*="type.css"] + link[href*="main.css"]', 'The `type.css` file must come before the `main.css` file']
      - '.grid'
      - '.grid > .unit'
      - 'img[src*="placeholder-triangle.svg"]'
      - '.masthead'
      - '.logo'
      - '.nav'
      - 'header h1'
      - 'header nav ul li a i'
    search:
      - 'Potion Express'
      - 'Unicorn Tears'
      - 'Dragon Scales'
      - 'Yeti Dandruff'
      - 'Pixie Dust'
      - 'xs-'
      - 's-'
      - 'm-'
      - 'l-'
      - 'push-?'
      - 'pad-?'
      - 'gutter-?'
      - 'island-?'
      - 'micro|milli|kilo|mega|giga|tera|peta|exa|zetta|yotta'
      - 'block'
      - ['list-group(?:-inline)?', 'The `.list-group` or `.list-group-inline` module should be used']

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['html', 'font-family', '"Abhaya Libre", serif']
      - ['.masthead', 'background-color']
      - ['.logo', 'text-align', 'center']
      - ['.nav', 'text-align', 'center']
      - ['@60em', '.logo', 'text-align', 'left']
      - ['@60em', '.nav', 'text-align', 'right']
    search:
      - '#fff'
      - '#15114c'
      - '#423ca3'
    search_not:
      - 'padding'
      - 'margin'
      - 'font-size'
      - 'list-style'
  - path: 'css/grid.css'
    valid: true
    bestPractices: true
    search:
      - ['https://gridifier.web-dev.tools/#xs,4,0,0,0;s,4,25,0,0;m,4,38,1,1;l,4,60,1,1', 'The `grid.css` should be generated with Gridifier’s default settings']
  - path: 'css/type.css'
    valid: true
    bestPractices: true
    search:
      - ['https://typografier.web-dev.tools/#0,100,1.3,1.067,0;38,110,1.4,1.125,1;60,120,1.5,1.125,1;90,130,1.5,1.125,1', 'The `type.css` should be generated with Typografier’s default settings']
  - path: 'css/modules.css'
    valid: true
    bestPractices: true
    search:
      - ['https://modulifier.web-dev.tools/#responsive;images;list-group;embed;media-object;icons;hidden;positioning;nice-lists;buttons;forms;accessibility;print', 'Select all the different modules when adding Modulifier.']

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 960, 1440]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('nav a');
        let oldBg = css(link).backgroundColor;

        hover('nav a', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the navigation links doesn’t change when hovered')
          pass();
        });
